# Generated by Django 3.2.25 on 2024-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cell_number', models.CharField(max_length=80)),
                ('user_date', models.DateField(max_length=50)),
            ],
        ),
    ]
