# Generated by Django 3.2.25 on 2024-08-31 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='identifier',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
