# Generated by Django 3.2.25 on 2024-09-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(default='')),
                ('idea_date', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('topic_date', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='IdeasTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ideas')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.topics')),
            ],
        ),
        migrations.AddField(
            model_name='ideas',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users'),
        ),
    ]
