# Generated by Django 3.2.25 on 2024-09-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240901_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(max_length=50)),
                ('ideaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ideas')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(default='')),
                ('comment_date', models.DateTimeField(max_length=50)),
                ('ideaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ideas')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users')),
            ],
        ),
    ]
