# Generated by Django 3.2.25 on 2024-09-01 21:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_users_user_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_roleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.userroles'),
            preserve_default=False,
        ),
    ]
