# Generated by Django 3.2.25 on 2024-09-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_users_user_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_roleID',
        ),
    ]
