# Generated by Django 3.2.25 on 2024-09-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_users_user_roleid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
