# Generated by Django 3.2.25 on 2024-09-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_roleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.userroles'),
        ),
    ]
